{{ config(
    materialized='incremental',
    unique_key='SURROGATE_KEY',
    incremental_strategy='merge',
    on_schema_change='sync_all_columns',
    alias= this.name ~ var('table_suffix', '')
    ) }}

WITH medicare AS (
SELECT SOURCE_SYSTEM
, SOURCE_SYSTEM_ID
, SOURCE_SYSTEM_ID_TYPE
, PREV_SOURCE_SYSTEM_ID
, PREV_SOURCE_SYSTEM_ID_TYPE
, SOURCE_SYSTEM_ID_2
, SOURCE_SYSTEM_ID_2_TYPE
, FIRST_NAME
, LAST_NAME
, FIRST_INITIAL
, LAST_INITIAL
, FIRST_NAME_SOUNDEX
, LAST_NAME_SOUNDEX
, DOB
, BIRTH_YEAR
, SEX
, RACE
, ADDRESS_LINE_1
, ADDRESS_LINE_2
, FULL_ADDRESS
, CITY
, STATE
, ZIP_5
, ZIP_4
, PHONE
, EMAIL
, DEATH_DATE
, SSN
, LOAD_DATE
, {{ dbt_utils.generate_surrogate_key(['SOURCE_SYSTEM_ID_TYPE', 'SOURCE_SYSTEM_ID']) }} AS SURROGATE_KEY
, LAST_UPDATED
FROM {{ ref('silver_bar') }}
{% if is_incremental() %}
WHERE LAST_UPDATED > (SELECT COALESCE(MAX(LAST_UPDATED), DATE '1900-01-01') FROM {{ this }} WHERE SOURCE_SYSTEM = 'BAR')
{% endif %}

UNION ALL

SELECT SOURCE_SYSTEM
, SOURCE_SYSTEM_ID
, SOURCE_SYSTEM_ID_TYPE
, PREV_SOURCE_SYSTEM_ID
, PREV_SOURCE_SYSTEM_ID_TYPE
, SOURCE_SYSTEM_ID_2
, SOURCE_SYSTEM_ID_2_TYPE
, FIRST_NAME
, LAST_NAME
, FIRST_INITIAL
, LAST_INITIAL
, FIRST_NAME_SOUNDEX
, LAST_NAME_SOUNDEX
, DOB
, BIRTH_YEAR
, SEX
, RACE
, ADDRESS_LINE_1
, ADDRESS_LINE_2
, FULL_ADDRESS
, CITY
, STATE
, ZIP_5
, ZIP_4
, PHONE
, EMAIL
, DEATH_DATE
, SSN
, LOAD_DATE
, {{ dbt_utils.generate_surrogate_key(['SOURCE_SYSTEM_ID_TYPE', 'SOURCE_SYSTEM_ID']) }} AS SURROGATE_KEY
, LAST_UPDATED
FROM {{ ref('silver_cclf8') }} c
WHERE NOT EXISTS (
    SELECT 1
    FROM {{ ref('silver_bar') }} AS b
    WHERE b.SOURCE_SYSTEM_ID = c.SOURCE_SYSTEM_ID
)
{% if is_incremental() %}
AND c.LAST_UPDATED > (SELECT COALESCE(MAX(LAST_UPDATED), DATE '1900-01-01') FROM {{ this }} WHERE SOURCE_SYSTEM = 'CCLF8')
{% endif %}
)

SELECT *
FROM medicare

UNION ALL

SELECT SOURCE_SYSTEM
, SOURCE_SYSTEM_ID
, SOURCE_SYSTEM_ID_TYPE
, PREV_SOURCE_SYSTEM_ID
, PREV_SOURCE_SYSTEM_ID_TYPE
, SOURCE_SYSTEM_ID_2
, SOURCE_SYSTEM_ID_2_TYPE
, FIRST_NAME
, LAST_NAME
, FIRST_INITIAL
, LAST_INITIAL
, FIRST_NAME_SOUNDEX
, LAST_NAME_SOUNDEX
, DOB
, BIRTH_YEAR
, SEX
, RACE
, ADDRESS_LINE_1
, ADDRESS_LINE_2
, FULL_ADDRESS
, CITY
, STATE
, ZIP_5
, ZIP_4
, PHONE
, EMAIL
, DEATH_DATE
, SSN
, LOAD_DATE
, {{ dbt_utils.generate_surrogate_key(['SOURCE_SYSTEM_ID_TYPE', 'SOURCE_SYSTEM_ID']) }} AS SURROGATE_KEY
, LAST_UPDATED
FROM {{ ref('silver_patient') }}
{% if is_incremental() %}
WHERE LAST_UPDATED > (SELECT COALESCE(MAX(LAST_UPDATED), DATE '1900-01-01') FROM {{ this }} WHERE SOURCE_SYSTEM = 'ATHENA')
{% endif %}