{{ config(
    materialized = 'incremental',
    unique_key = 'SOURCE_SYSTEM_ID',
    incremental_strategy = 'merge',
    on_schema_change = 'sync_all_columns',
    alias= this.name ~ var('table_suffix', '')
)}}

WITH src AS (
SELECT 'ATHENA' AS SOURCE_SYSTEM
, UPPER(TRIM(PATIENTID)) AS SOURCE_SYSTEM_ID
, 'PATIENTID' AS SOURCE_SYSTEM_ID_TYPE
, TO_VARCHAR(ENTERPRISEID) AS SOURCE_SYSTEM_ID_2
, 'ENTERPRISEID' AS SOURCE_SYSTEM_ID_2_TYPE
, UPPER(REGEXP_REPLACE(TRIM(FIRSTNAME), '\s+', ' ')) AS FIRST_NAME
, UPPER(REGEXP_REPLACE(TRIM(LASTNAME), '\s+', ' ')) AS LAST_NAME
, TRY_TO_DATE(DOB) AS DOB
, UPPER(TRIM(SEX)) AS SEX
, UPPER(TRIM(RACE)) AS RACE
, UPPER(REGEXP_REPLACE(TRIM("ADDRESS"), '\s+', ' ')) AS ADDRESS_LINE_1
, NULLIF(UPPER(REGEXP_REPLACE(TRIM(ADDRESS2), '\s+', ' ')), '') AS ADDRESS_LINE_2
, UPPER(REGEXP_REPLACE(TRIM(CITY), '\s+', ' ')) AS CITY
, UPPER(REGEXP_REPLACE(TRIM(STATE), '\s+', ' ')) AS STATE
, TRIM(ZIP) AS ZIP
, REGEXP_REPLACE(TRIM(PATIENTHOMEPHONE), '[^0-9]', '') AS PATIENTHOMEPHONE
, REGEXP_REPLACE(TRIM(MOBILEPHONE), '[^0-9]', '') AS MOBILEPHONE
, REGEXP_REPLACE(TRIM(WORKPHONE), '[^0-9]', '') AS WORKPHONE
, TRIM(EMAIL) AS EMAIL
, TRY_TO_DATE(DECEASEDDATE) AS DEATH_DATE
, TRIM(PATIENTSSN) AS SSN
, CAST(LASTUPDATED AS DATE) AS LOAD_DATE
FROM {{ source('ATHENA_EMR', 'PATIENT') }}
WHERE TESTPATIENTYN = 'N'
{% if is_incremental() %}
AND CAST(LASTUPDATED AS DATE) > (SELECT COALESCE(MAX(LOAD_DATE), DATE '1900-01-01') FROM {{ this }})
{% endif %}
)

, normalized as (
SELECT SOURCE_SYSTEM
, SOURCE_SYSTEM_ID
, SOURCE_SYSTEM_ID_TYPE
, NULL AS PREV_SOURCE_SYSTEM_ID
, NULL AS PREV_SOURCE_SYSTEM_ID_TYPE
, SOURCE_SYSTEM_ID_2
, SOURCE_SYSTEM_ID_2_TYPE
, FIRST_NAME
, LAST_NAME
, LEFT(FIRST_NAME, 1) AS FIRST_INITIAL
, LEFT(LAST_NAME, 1) AS LAST_INITIAL
, SOUNDEX(FIRST_NAME) AS FIRST_NAME_SOUNDEX
, SOUNDEX(LAST_NAME) AS LAST_NAME_SOUNDEX
, DOB
, YEAR(DOB) AS BIRTH_YEAR
, SEX
, RACE
, ADDRESS_LINE_1
, ADDRESS_LINE_2
, CONCAT(ADDRESS_LINE_1, COALESCE(CONCAT(' ', ADDRESS_LINE_2), '')) AS FULL_ADDRESS
, CITY
, STATE
, CASE 
    WHEN LENGTH(ZIP) >= 5 AND NOT REGEXP_LIKE(ZIP, '0{5}|1{5}|2{5}|3{5}|4{5}|5{5}|6{5}|7{5}|8{5}|9{5}') THEN LEFT(ZIP, 5)
    WHEN LENGTH(ZIP) = 4 AND NOT REGEXP_LIKE(ZIP, '0{4}|1{4}|2{4}|3{4}|4{4}|5{4}|6{4}|7{4}|8{4}|9{4}') THEN LPAD(ZIP, 5, '0')
END AS ZIP_5
, CASE 
    WHEN LENGTH(ZIP) IN (9,10) THEN RIGHT(ZIP, 4)
END AS ZIP_4
, CASE
    WHEN LENGTH(PATIENTHOMEPHONE) = 10 AND NOT REGEXP_LIKE(PATIENTHOMEPHONE, '0{10}|1{10}|2{10}|3{10}|4{10}|5{10}|6{10}|7{10}|8{10}|9{10}') THEN PATIENTHOMEPHONE
    WHEN LENGTH(MOBILEPHONE) = 10 AND NOT REGEXP_LIKE(MOBILEPHONE, '0{10}|1{10}|2{10}|3{10}|4{10}|5{10}|6{10}|7{10}|8{10}|9{10}') THEN MOBILEPHONE
    WHEN LENGTH(WORKPHONE) = 10 AND NOT REGEXP_LIKE(WORKPHONE, '0{10}|1{10}|2{10}|3{10}|4{10}|5{10}|6{10}|7{10}|8{10}|9{10}') THEN WORKPHONE
END AS PHONE
, CASE
    WHEN REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$') 
        AND NOT REGEXP_LIKE(EMAIL, '.*(NONGIVEN|NOGIVEN|NONEGIVEN|NONGIVIN|SCHEDULING|NOEMAIL|NOREPLY|DECLINED|NOTAVAILABLE).*', 'i') THEN UPPER(EMAIL)
END AS EMAIL
, DEATH_DATE
, CASE
    WHEN LENGTH(SSN) = 9 AND NOT REGEXP_LIKE(SSN, '0{9}|1{9}|2{9}|3{9}|4{9}|5{9}|6{9}|7{9}|8{9}|9{9}') THEN SSN
END AS SSN
, LOAD_DATE
FROM src
)

, hashed_cte as (
select *
, {{ dbt_utils.generate_surrogate_key(['FIRST_NAME', 'LAST_NAME', 'DOB', 'SEX', 'ADDRESS_LINE_1', 'ZIP_5', 'DEATH_DATE', 'SSN', 'PHONE', 'EMAIL']) }} AS DEMO_HASH
from normalized
)

, staged as (
   SELECT h.*
    {% if is_incremental() %}
    , CASE
        WHEN t.load_date IS NULL THEN h.load_date
        ELSE t.first_load_date
    END AS first_load_date 
    {% else %}
    , h.load_date AS first_load_date
    {% endif %} 
    , convert_timezone('UTC', current_timestamp())::timestamp_ntz AS last_updated
    FROM hashed_cte h
    {% if is_incremental() %}
    LEFT JOIN {{ this }} t
    ON h.source_system_id = t.source_system_id
    WHERE h.demo_hash <> t.demo_hash
    OR t.source_system_id IS NULL
    {% endif %}
)

SELECT *
FROM staged s
