-- EXAMPLE SETUP of RBAC for a snowflake service user to run dbt cloud jobs

-- CREATE SVC ROLE
CREATE ROLE IF NOT EXISTS DBT_SVC_PROD;

-- GRANT USAGE ON RELEAVNT DB, SCHEMA, AND COMPUTE_WH
GRANT USAGE ON DATABASE UPPERLINE_TEST TO ROLE DBT_SVC_PROD;
GRANT USAGE ON SCHEMA UPPERLINE_TEST.DEV TO ROLE DBT_SVC_PROD;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_SVC_PROD;

-- GRANT PRIVS ON TABLES/VIEWS (CREATE + SELECT)
GRANT OWNERSHIP ON SCHEMA UPPERLINE_TEST.DEV TO ROLE DBT_SVC_PROD COPY CURRENT GRANTS; -- NEEDED TO ALLOW DROP/RECREATING TABLES THAT ALREADY EXIST
GRANT CREATE SCHEMA ON DATABASE UPPERLINE_TEST TO ROLE DBT_SVC_PROD;
GRANT CREATE TABLE ON SCHEMA UPPERLINE_TEST.DEV TO ROLE DBT_SVC_PROD;
GRANT CREATE VIEW ON SCHEMA UPPERLINE_TEST.DEV TO ROLE DBT_SVC_PROD;
GRANT SELECT ON ALL TABLES IN SCHEMA UPPERLINE_TEST.DEV TO ROLE DBT_SVC_PROD;
GRANT SELECT ON ALL VIEWS IN SCHEMA UPPERLINE_TEST.DEV TO ROLE DBT_SVC_PROD;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UPPERLINE_TEST.DEV TO ROLE DBT_SVC_PROD;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA UPPERLINE_TEST.DEV TO ROLE DBT_SVC_PROD;

-- CONFIRM GRANTS ON ROLE
SHOW GRANTS TO ROLE DBT_SVC_PROD;

-- CREATE USER AND ASSIGN THE ROLE
CREATE OR REPLACE USER DBT_SVC_PROD
    DEFAULT_ROLE = DBT_SVC_PROD -- SETS THE DEFAULT ROLE BUT DOESNT GRANT IT
    TYPE = SERVICE
    DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE DBT_SVC_PROD TO USER DBT_SVC_PROD;


-- DISPLAY USERS AND VERIFY THE SVC ROLE WAS CREATED CORRECTLY
SHOW USERS;

-- AFTER CREATE RSA KEY-PAIR, ATTACH THE PUBLC KEY TO THE SERVICE ROLE WITHOUT HEADER/FOOTER
ALTER USER DBT_SVC_PROD
    SET RSA_PUBLIC_KEY = '<PUBLIC_KEY_STRING>';

    