-- EXAMPLE SETUP of RBAC for a snowflake service user to run dbt cloud jobs

-- assumes the following roles exist: DBT_STG_ROLE and DBT_PROD_ROLE

-- UPPERLINE_REFINED.DBT_EMPI_STG --> setting up the necessary privs for the staging role
GRANT USAGE ON SCHEMA UPPERLINE.CORE TO ROLE DBT_STG_ROLE;
GRANT USAGE ON SCHEMA UPPERLINE.STAGING TO ROLE DBT_STG_ROLE;
GRANT CREATE TABLE ON SCHEMA UPPERLINE_REFINED.DBT_EMPI_STG TO ROLE DBT_STG_ROLE;
GRANT CREATE VIEW ON SCHEMA UPPERLINE_REFINED.DBT_EMPI_STG TO ROLE DBT_STG_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA UPPERLINE.CORE TO ROLE DBT_STG_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA UPPERLINE.STAGING TO ROLE DBT_STG_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UPPERLINE.CORE TO ROLE DBT_STG_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UPPERLINE.STAGING TO ROLE DBT_STG_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA UPPERLINE.CORE TO ROLE DBT_STG_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA UPPERLINE.STAGING TO ROLE DBT_STG_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA UPPERLINE.CORE TO ROLE DBT_STG_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA UPPERLINE.STAGING TO ROLE DBT_STG_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE ATHENAHEALTH TO ROLE DBT_STG_ROLE;

-- UPPERLINE_REFINED.EMPI --> setting up the necessary privs for the production role
GRANT USAGE ON SCHEMA UPPERLINE.CORE TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA UPPERLINE.STAGING TO ROLE DBT_PROD_ROLE;
GRANT CREATE TABLE ON SCHEMA UPPERLINE_REFINED.EMPI TO ROLE DBT_PROD_ROLE;
GRANT CREATE VIEW ON SCHEMA UPPERLINE_REFINED.EMPI TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA UPPERLINE.CORE TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA UPPERLINE.STAGING TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UPPERLINE.CORE TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA UPPERLINE.STAGING TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA UPPERLINE.CORE TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA UPPERLINE.STAGING TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA UPPERLINE.CORE TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA UPPERLINE.STAGING TO ROLE DBT_PROD_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE ATHENAHEALTH TO ROLE DBT_PROD_ROLE;

    