-- FOR STREAMLIT APPS
-- EMPI_STEWARD (needs read/write access to link/unlink overrides table and the gold EMPI crosswalk view)
CREATE ROLE IF NOT EXISTS EMPI_STEWARD;
GRANT USAGE ON DATABASE UPPERLINE_REFINED TO ROLE EMPI_STEWARD;
GRANT USAGE ON SCHEMA UPPERLINE_REFINED.DBT_EMPI_STG TO ROLE EMPI_STEWARD;
GRANT USAGE ON SCHEMA UPPERLINE_REFINED.EMPI TO ROLE EMPI_STEWARD;
GRANT USAGE ON WAREHOUSE ACRATICA_WH TO ROLE EMPI_STEWARD;
GRANT SELECT, INSERT, UPDATE ON TABLE UPPERLINE_REFINED.DBT_EMPI_STG.EMPI_LINK_UNLINK_OVERRIDES TO ROLE EMPI_STEWARD;
GRANT SELECT ON VIEW UPPERLINE_REFINED.EMPI.EMPI_CROSSWALK_GOLD TO ROLE EMPI_STEWARD;
GRANT READ SESSION ON ACCOUNT TO ROLE EMPI_STEWARD;
GRANT USAGE ON STREAMLIT UPPERLINE_REFINED.EMPI.EMPI_LINK_UNLINK_UI_PROD TO ROLE EMPI_STEWARD;

-- EMPI_APPROVER Role (needs read access to link/unlink overrides table)
CREATE ROLE IF NOT EXISTS EMPI_APPROVER;
GRANT USAGE ON DATABASE UPPERLINE_REFINED TO ROLE EMPI_APPROVER;
GRANT USAGE ON SCHEMA UPPERLINE_REFINED.DBT_EMPI_STG TO ROLE EMPI_APPROVER;
GRANT USAGE ON SCHEMA UPPERLINE_REFINED.EMPI TO ROLE EMPI_APPROVER;
GRANT USAGE ON WAREHOUSE ACRATICA_WH TO ROLE EMPI_APPROVER;
GRANT SELECT, INSERT, UPDATE ON TABLE UPPERLINE_REFINED.DBT_EMPI_STG.EMPI_LINK_UNLINK_OVERRIDES TO ROLE EMPI_APPROVER;
GRANT READ SESSION ON ACCOUNT TO ROLE EMPI_APPROVER;
GRANT USAGE ON STREAMLIT UPPERLINE_REFINED.EMPI.EMPI_APPROVALS_UI_PROD TO ROLE EMPI_APPROVER;