-- Examples roles setup for streamlit apps in Snowflake.  use this as a template and modify as needed.

-- Link/Unlink App Role (needs read/write access to link/unlink overrides table and the EMPI crosswalk table)
CREATE OR REPLACE ROLE IF NOT EXISTS LINK_UNLINK_APP_ROLE;
GRANT USAGE ON DATABASE <'DATABASE_NAME'> TO ROLE LINK_UNLINK_APP_ROLE;
GRANT USAGE ON SCHEMA <'DATABASE_NAME'>.<'SCHEMA_NAME'> TO ROLE LINK_UNLINK_APP_ROLE;
GRANT USAGE ON WAREHOUSE <'WAREHOUSE_NAME'> TO ROLE LINK_UNLINK_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE <'DATABASE_NAME'>.<'SCHEMA_NAME'>.empi_link_unlink_overrides TO ROLE LINK_UNLINK_APP_ROLE;
GRANT SELECT ON TABLE <'DATABASE_NAME'>.<'SCHEMA_NAME'>.det_empi_crosswalk TO ROLE LINK_UNLINK_APP_ROLE;
GRANT READ SESSION ON ACCOUNT TO ROLE LINK_UNLINK_APP_ROLE;

-- Approvals App Role (needs read access to link/unlink overrides table)
CREATE OR REPLACE ROLE IF NOT EXISTS APPROVALS_APP_ROLE;
GRANT USAGE ON DATABASE <'DATABASE_NAME'> TO ROLE APPROVALS_APP_ROLE;
GRANT USAGE ON SCHEMA <'DATABASE_NAME'>.<'SCHEMA_NAME'> TO ROLE APPROVALS_APP_ROLE;
GRANT USAGE ON WAREHOUSE <'WAREHOUSE_NAME'> TO ROLE APPROVALS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE <'DATABASE_NAME'>.<'SCHEMA_NAME'>.empi_link_unlink_overrides TO ROLE APPROVALS_APP_ROLE;
GRANT READ SESSION ON ACCOUNT TO ROLE APPROVALS_APP_ROLE;